server:
  port: 8080

spring:
  application:
    name: final_project

  mail:
     host: smtp.gmail.com
     port: 587
     username: dlrjsgh951@gmail.com
     password: "edqq xbvb adzu rzwt"
     properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

  # DB ?? ??
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: semicolon
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.OracleDialect

  servlet:
    multipart:
      enabled: true
      max-request-size: 30MB # 전체 요청의 최대 크기
      max-file-size: 10MB    # 개별 파일의 최대 크기

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type: TRACE


com:
    semicolon:
        backend:
          upload: C:/dev/upload

jwt:
    secret:


portone:
  store-id: "store-b3883a44-ac75-4cff-8df1-e77a3dea43b0"
  channel-key: "channel-key-69ba4122-ea56-4238-a168-f5026d6b6ba3"
  api-url: "https://api.portone.io"
  api-secret: ${PORTONE_API_SECRET}